source 'https://rubygems.org'

gem 'rails', '4.1.7'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'haml', '~> 4.0.6'
gem 'simple_form', '~> 3.1.0'
gem 'devise', '~> 3.4.1'
gem 'acts_as_votable', '~> 0.10.0'
gem 'geocoder', '~> 1.2.8'
gem 'friendly_id', '~> 5.1.0'
gem 'searchkick', '~> 0.8.7'
gem 'will_paginate', '~> 3.0.7'